name: Platform Delivery Pipeline

concurrency:
  group: terraform-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

on:
  workflow_run:
    workflows: ["Hello Platform Service CI"]
    types: [completed]


jobs:
  setup:
    if: >
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.get_metadata.outputs.env_name }}
      tf_dir: ${{ steps.set_env.outputs.tf_dir }}
      app_version: ${{ steps.get_metadata.outputs.version }}
    steps:
      - name: Download Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: pipeline-metadata
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - id: get_metadata
        run: |
          VERSION=$(cat app_version.txt)
          ENV_NAME=$(cat env_name.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "env_name=$ENV_NAME" >> $GITHUB_OUTPUT

      - id: set_env
        run: |
          BRANCH="${{ github.event.workflow_run.head_branch }}"
          if [[ "$BRANCH" == "main" ]]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == release/* ]]; then
            echo "env_name=qa" >> $GITHUB_OUTPUT
          else
            echo "env_name=dev" >> $GITHUB_OUTPUT
          fi
          echo "tf_dir=terraform" >> $GITHUB_OUTPUT

  deploy:
    needs: [ setup ]
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.env_name }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout to access local action
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Common Setup
        uses: ./.github/workflows/cd-actions/tf-setup
        with:
          wif_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.CD_SA_EMAIL }}

      - name: Terraform Apply
        run: |
          cd ${{ needs.setup.outputs.tf_dir }}
          terraform init \
            -var="env=${{ needs.setup.outputs.env_name }}" \
            -backend-config="bucket=hello-platform-terraform-${{ needs.setup.outputs.env_name }}" \
            -backend-config="prefix=env/${{ needs.setup.outputs.env_name }}"
          terraform apply -auto-approve \
            -var="env=${{ needs.setup.outputs.env_name }}" \
            -var="project_id=${{ vars.GCP_PROJECT_ID }}" \
            -var="service_name=${{ vars.SERVICE_NAME }}" \
            -var="image_url=${{ vars.REGISTRY_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/hello-platform-artifact-registry/${{ vars.SERVICE_NAME }}:${{ needs.setup.outputs.app_version }}" \
            -var="commit_sha=${{ github.event.workflow_run.head_sha }}"