name: Hello Platform Service CI

on:
  pull_request:
    branches: [ develop, "release/*", main ]
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  id-token: write


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set_env.outputs.env_name }}
      tf_dir: ${{ steps.set_env.outputs.tf_dir }}
      app_version: ${{ steps.project_version.outputs.app_version }}
    steps:
      - id: set_env
        run: |
          # Use base_ref for PRs, or ref for direct pushes (merges)
          BRANCH="${{ github.base_ref || github.ref_name }}"
          if [[ "$BRANCH" == "main" ]]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
            echo "tf_dir=terraform" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == release/* ]]; then
            echo "env_name=qa" >> $GITHUB_OUTPUT
            echo "tf_dir=terraform" >> $GITHUB_OUTPUT
          else
            echo "env_name=dev" >> $GITHUB_OUTPUT
            echo "tf_dir=terraform" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Extract Maven Version
        id: project_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "app_version=$VERSION" >> $GITHUB_OUTPUT
          # Create files for the CD pipeline to consume
          echo "$VERSION" > app_version.txt
          echo "${{ steps.set_env.outputs.env_name }}" > env_name.txt

      - name: Upload Metadata
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-metadata
          path: |
            app_version.txt
            env_name.txt
  validate:
    needs: [ setup ]
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.env_name }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # Step 1: Checkout the main repo so GitHub can find the local action
      - name: Checkout to access local action
        uses: actions/checkout@v4

      # Step 2: Run the local action and pass the necessary GCP variables
      - name: Common Setup
        uses: ./.github/workflows/cd-actions/tf-setup
        with:
          wif_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.CD_SA_EMAIL }}

      - name: Terraform Format Check
        run: |
          cd ${{ needs.setup.outputs.tf_dir }}
          terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd ${{ needs.setup.outputs.tf_dir }}
          terraform init -backend=false
          terraform validate

  build-and-scan:
    needs: [ setup, validate ]
    if: github.base_ref != 'main' && github.ref_name != 'main'
    environment: ${{ needs.setup.outputs.env_name }}
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT: ${{ vars.GCP_PROJECT_ID }}
      WIF_PROVIDER: ${{ vars.WIF_PROVIDER }}
      SERVICE_ACCOUNT: ${{ vars.SA_EMAIL }}
      REGISTRY_REGION: ${{ vars.REGISTRY_REGION }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      # Full registry path for consistency
      FULL_IMAGE_PATH: ${{ vars.REGISTRY_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/hello-platform-artifact-registry/${{ vars.IMAGE_NAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven Checkstyle
        run: mvn checkstyle:check

      - name: Run Unit Tests
        run: mvn clean test

      - name: GCP Auth (Keyless via WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.REGISTRY_REGION }}-docker.pkg.dev

      # Build and Load locally so Trivy can see it
      - name: Build Local Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.FULL_IMAGE_PATH }}:${{ github.sha }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            APP_VERSION=${{ needs.setup.outputs.app_version }}

      # Requirement: Run vulnerability scan
      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.FULL_IMAGE_PATH }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # Fails the build if issues are found
          severity: 'CRITICAL,HIGH'


      - name: Build and Push to Artifact Registry
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.FULL_IMAGE_PATH }}:${{ github.sha }}
            ${{ env.FULL_IMAGE_PATH }}:${{ needs.setup.outputs.app_version }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            APP_VERSION=${{ needs.setup.outputs.app_version }}

    # New job to handle versioning when we skip the full build
  promote-metadata:
    needs: [ setup ]
    if: github.base_ref == 'main' || github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Promoting version ${{ needs.setup.outputs.app_version }} to Production"